baseURL = 'https://fixthesupremecourt.org/'
languageCode = 'en-us'
title = 'Fix The Supreme Court'
theme = 'PaperMod'

[params]
mainSections = ['posts', 'featured']
defaultTheme = 'light'
summaryLength = 500

[params.label]
text = ""
icon = "logo_circle.png"
iconHeight = 60

[pagination]
pagerSize = 20
